#!/bin/bash

echo "" > output.txt

for i in ../testcases/*
do
	echo "Parse.parse \"$i\";" | sml sources.cm >> output.txt
done

count=`grep "error" output.txt | wc -l`

fileCount=`ls -1 ../testcases | wc -l`

echo "$count errors out of $fileCount tests."