#!/bin/bash

echo "CM.make \"sources.cm\";" > output.sml

for i in ../testcases/*
do
    echo "TextIO.output (TextIO.stdOut, \"Parsing $i...............\n\");" >> output.sml
    echo "PrintAbsyn.print (TextIO.stdOut, Parse.parse \"$i\");" >> output.sml
done
echo "OS.Process.exit(OS.Process.success);" >> output.sml

sml output.sml > output.txt
echo "Failed testcases: "
grep "error:" output.txt